// CATEGORIES
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";

// PRODUCTS
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS";

// CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
