// CATEGORIES
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";

// PRODUCTS
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS";

// CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

// TIMER
export const TIMER_TICK = "TIMER_TICK";
export const TIMER_START = "TIMER_START";
export const TIMER_STOP = "TIMER_STOP";
